eurekaserver:
   image:   tmx-eurekasvr:chapter4
   ports:
       - "8761:8761"

configserver:
    image: tmx-confsvr:chapter4
    ports:
       - "8888:8888"
    links:
       - "eurekaserver:eurekaserver"
    environment:
       EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"

# configserver2:
#     image: tmx-confsvr:chapter4
#     ports:
#        - "8889:8889"
#     links:
#         - "eurekaserver:eurekaserver"
#     environment:
#       EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"

database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p0stgr@s
      - POSTGRES_DB=eagle_eye_local

licensingservice:
    image: tmx-licensing-service:chapter4
    ports:
      - "8080:8080"
    links:
      - "database:database"
      - "configserver:configserver"
      - "eurekaserver:eurekaserver"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8080"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"

organizationservice:
    image: tmx-organization-service:chapter4
    ports:
      - "8085:8085"
    links:
      - "database:database"
      - "configserver:configserver"
      - "eurekaserver:eurekaserver"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8085"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"

organizationservice2:
    image: tmx-organization-service:chapter4
    ports:
      - "8086:8086"
    links:
      - "database:database"
      - "configserver:configserver"
      - "eurekaserver:eurekaserver"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8085"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
